
vmsacars_config:
  ignore_on_update:
    - 'value'
  data:
    - id: 'license_key'
      name: 'Your vmsACARS license key'
      order: 1
      value: ''
      default: ''
      options: ''
      type: 'string'
      description: 'The license key for vmsACARS. You can retrieve this from your host dashboard'
    - id: 'bids_only'
      name: 'Only show bids'
      order: 3
      value: ''
      default: 'true'
      options: ''
      type: 'bool'
      description: 'Only show bids in the flight list'
    - id: 'use_real_time'
      name: 'Use the system time, not the in-sim time'
      order: 5
      value: 'false'
      default: 'false'
      type: 'bool'
      description: 'For flight times, use the system time instead of the in-sim time'
    - id: 'fares_required'
      name: 'Fare entry is required'
      order: 6
      value: 'true'
      default: 'true'
      type: 'bool'
      description: 'Entries for the fares are required to be entered'
    - id: 'acars_update_timer'
      name: 'ACARS update timer (in seconds)'
      order: 7
      value: '30'
      default: '30'
      options: '15, 30, 60, 90, 120, 240, 300, 360, 480'
      type: 'select'
      description: 'How often the ACARS map updates flights'
    - id: 'position_report_ground'
      name: 'Ground position report interval (in seconds)'
      order: 9
      value: '15'
      default: '15'
      options: '15, 30, 60, 90, 120, 240, 300, 360, 480'
      type: 'select'
      description: ''
    - id: 'position_report_under_transition'
      name: 'Position report interval (< 18k), in seconds'
      order: 12
      value: '90'
      default: '60'
      options: '15, 30, 60, 90, 120, 240, 300, 360, 480'
      type: 'select'
      description: ''
    - id: 'position_report_above_transition'
      name: 'Position report interval (> 18k), in seconds'
      order: 15
      value: '300'
      default: '60'
      options: '15, 30, 60, 90, 120, 240, 300, 360, 480'
      type: 'select'
      description: ''
